## Cleaning Different Sheets from the Same File in Python

In [370]:
# import pandas
import pandas as pd

### Load dataset

In [371]:
financial_inclusion = pd.read_excel(
    r"c:\Users\TOSHIBA\Desktop\INTERNSHIP\Financial Inclusion Dataset.xlsx",
    sheet_name=["Money Supply", "Mobile Money","Interest Rate"],
    engine="openpyxl"
)

In [372]:
money_supply = financial_inclusion["Money Supply"]
mobile_money = financial_inclusion["Mobile Money"]
interest_rate = financial_inclusion["Interest Rate"]

### Preview

In [373]:
money_supply.head()

,Year,Variables,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,2023,Money Supply_Total Liquidity (M2+) (Millions o...,196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017,Money Supply_ Narrow Money (M1) (Millions of ...,91213.65,92444.84,94959.70,97523.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017,Money Supply_Broad Money (M2) (Millions of Gha...,139966.12,143732.50,148131.00,150496.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017,Money Supply_Reserve Money (RM) (Millions of G...,62752.24,66660.76,57840.77,69161.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017,Total Liabilities of the Bankning System (Mill...,196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### intia Inspection

In [374]:
# check structure
money_supply.info()

# check summary stats
money_supply.describe()

# check missing values
money_supply.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       450 non-null    int64
 1   Variables  450 non-null    object
 2   Jan        450 non-null    float64
 3   Feb        450 non-null    float64
 4   Mar        450 non-null    float64
 5   Apr        450 non-null    float64
 6   May        450 non-null    float64
 7   Jun        450 non-null    float64
 8   Jul        450 non-null    float64
 9   Aug        450 non-null    float64
 10  Sep        450 non-null    float64
 11  Oct        450 non-null    float64
 12  Nov        450 non-null    float64
 13  Dec        450 non-null    float64
dtypes: float64(12), int64(1), object(1)
memory usage: 49.3+ KB

Year         0
Variables    0
Jan          0
Feb          0
Mar          0
Apr          0
May          0
Jun          0
Jul          0
Aug          0
Sep          0
Oct          0
Nov          0
Dec          0
dtype: int64

### Clean column names

In [375]:
money_supply.rename(columns ={
    "Variables":"Variable",
    "Jan":"January",
    "Feb":"Febuary",
    "Mar":"March",
    "Apr":"April",
    "Jun":"June",
    "Jul":"July",
    "Aug":"August",
    "Sep":"September",
    "Oct":"October",
    "Nov":"November",
    "Dec":"December"}, inplace =True)

In [376]:
money_supply

,Year,Variable,January,Febuary,March,April,May,June,July,August,September,October,November,December
0,2023,Money Supply_Total Liquidity (M2+) (Millions o...,196993.67,201602.75,206824.35,207528.19,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2017,Money Supply_ Narrow Money (M1) (Millions of ...,91213.65,92444.84,94959.70,97523.05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2017,Money Supply_Broad Money (M2) (Millions of Gha...,139966.12,143732.50,148131.00,150496.16,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2017,Money Supply_Reserve Money (RM) (Millions of G...,62752.24,66660.76,57840.77,69161.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2017,Total Liabilities of the Bankning System (Mill...,196993.67,201602.75,206824.35,207528.19,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,2000,Net Domestic Assets_Claims on Govt. (Millions ...,617.33,802.97,932.59,1104.29,1340.40,1483.62,1698.81,1931.28,2113.97,2354.68,2591.27,575.45
446,2000,Net Domestic Assets (Millions of Ghana Cedis),484.74,487.03,508.73,515.54,543.88,530.66,614.51,630.12,651.49,673.94,704.58,756.27
447,2000,Net Foreign Assets_DMBs (Millions of Ghana Cedis),23.94,16.13,18.13,26.23,37.05,29.35,25.77,19.44,21.78,38.36,27.65,-1.38
448,2000,Net Foreign Assets_BOG (Millions of Ghana Cedis),-15.76,-6.53,-12.19,-12.89,-36.40,4.72,-52.33,-48.91,-46.26,-70.54,-39.53,-30.08
449,2000,Net Foreign Assets (Millions of Ghana Cedis),8.19,9.59,5.94,13.35,0.64,34.07,-26.56,-29.47,-24.48,-32.17,-11.88,-31.46

### Remove (Millions of Ghana cedis) from Variable column using regex

In [377]:
money_supply["Variable"] = money_supply["Variable"].str.replace(r"\(Millions.*?\)"," ", regex=True)

In [378]:
money_supply.head()

,Year,Variable,January,Febuary,March,April,May,June,July,August,September,October,November,December
0,2023,Money Supply_Total Liquidity (M2+),196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017,Money Supply_ Narrow Money (M1),91213.65,92444.84,94959.70,97523.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017,Money Supply_Broad Money (M2),139966.12,143732.50,148131.00,150496.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017,Money Supply_Reserve Money (RM),62752.24,66660.76,57840.77,69161.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017,Total Liabilities of the Bankning System,196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Check data types

In [379]:
money_supply.dtypes

Year           int64
Variable      object
January      float64
Febuary      float64
March        float64
April        float64
May          float64
June         float64
July         float64
August       float64
September    float64
October      float64
November     float64
December     float64
dtype: object

### Remove Years before 2017

In [380]:
money_supply = money_supply[money_supply["Year"]>=2017]

In [381]:
money_supply.head()

,Year,Variable,January,Febuary,March,April,May,June,July,August,September,October,November,December
0,2023,Money Supply_Total Liquidity (M2+),196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017,Money Supply_ Narrow Money (M1),91213.65,92444.84,94959.70,97523.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017,Money Supply_Broad Money (M2),139966.12,143732.50,148131.00,150496.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017,Money Supply_Reserve Money (RM),62752.24,66660.76,57840.77,69161.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017,Total Liabilities of the Bankning System,196993.67,201602.75,206824.35,207528.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Reshape the dataset by converting months into rows

In [382]:
money_supply=money_supply.melt(
    id_vars=["Year","Variable"],
    value_vars=["January","Febuary","March","April","May","June","July","August","September","October","November","December"],
    var_name="Month",
    value_name="Value"
)

In [383]:
money_supply

      Year                                    Variable     Month      Value
0     2023        Money Supply_Total Liquidity (M2+)     January  196993.67
1     2017          Money Supply_ Narrow Money  (M1)     January   91213.65
2     2017             Money Supply_Broad Money (M2)     January  139966.12
3     2017           Money Supply_Reserve Money (RM)     January   62752.24
4     2017  Total Liabilities of the Bankning System     January  196993.67
...    ...                                         ...       ...        ...
1723  2023       Net Domestic Assets_Claims on Govt.    December   23632.56
1724  2023                       Net Domestic Assets    December   45999.08
1725  2023                   Net Foreign Assets_DMBs    December    3438.28
1726  2023                    Net Foreign Assets_BOG    December   16900.50
1727  2023                        Net Foreign Assets    December   20338.78

[1728 rows x 4 columns]

### Check if there are missing values

In [384]:
money_supply.isnull().sum()

Year        0
Variable    0
Month       0
Value       0
dtype: int64

### Check if any empty value exists

In [385]:
money_supply.isnull().values.any()

False

### Count the total number of zero

In [386]:
(money_supply["Value"]==0).sum()

180

### View rows with zeros values

In [387]:
money_supply[money_supply["Value"]==0]

      Year                                    Variable     Month  Value
576   2023        Money Supply_Total Liquidity (M2+)         May    0.0
577   2017          Money Supply_ Narrow Money  (M1)         May    0.0
578   2017             Money Supply_Broad Money (M2)         May    0.0
579   2017           Money Supply_Reserve Money (RM)         May    0.0
580   2017  Total Liabilities of the Bankning System         May    0.0
...    ...                                         ...       ...    ...
1615  2018       Net Domestic Assets_Claims on Govt.    December    0.0
1634  2019                   Net Foreign Assets_DMBs    December    0.0
1635  2019                       Net Domestic Assets    December    0.0
1636  2019                    Net Foreign Assets_BOG    December    0.0
1637  2019                        Net Foreign Assets    December    0.0

[180 rows x 4 columns]

### Group by variable

In [388]:
money_supply[money_supply["Value"]==0].groupby("Variable").size()

Variable
Money Supply Component_Currency outside banks                                             10
Money Supply Component_Demand deposits                                                    10
Money Supply Component_Foreign currency deposits                                          10
Money Supply Component_Savings & Time deposits                                            10
Money Supply_ Narrow Money  (M1)                                                          10
Money Supply_Broad Money (M2)                                                             10
Money Supply_Reserve Money (RM)                                                           10
Money Supply_Total Liquidity (M2+)                                                        10
Net Domestic Assets                                                                       10
Net Domestic Assets_Claims on Govt.                                                       10
Net Domestic Assets_Claims on Private Sector & Public Net Domestic Assets_Enterprise      10
Net Domestic Assets_Govt. Deposits                                                        10
Net Domestic Assets_Other Items (net)                                                     10
Net Foreign Assets                                                                        10
Net Foreign Assets_BOG                                                                    10
Net Foreign Assets_DMBs                                                                   10
Total Assets of the Banking System                                                        10
Total Liabilities of the Bankning System                                                  10
dtype: int64

### Check if zeros cluster in specific months

In [389]:
money_supply[money_supply["Value"]==0].groupby("Month").size()

Month
August       18
December     36
July         18
June         18
May          18
November     36
October      18
September    18
dtype: int64

### Remove Duplicate

In [390]:
money_supply = money_supply.drop_duplicates()

### Final dataset Preview

In [391]:
money_supply.head()

   Year                                    Variable    Month      Value
0  2023        Money Supply_Total Liquidity (M2+)    January  196993.67
1  2017          Money Supply_ Narrow Money  (M1)    January   91213.65
2  2017             Money Supply_Broad Money (M2)    January  139966.12
3  2017           Money Supply_Reserve Money (RM)    January   62752.24
4  2017  Total Liabilities of the Bankning System    January  196993.67

### Export clean data

In [392]:
money_supply.to_excel(r"C:\Users\TOSHIBA\Desktop\py\Money Supply.xlsx", index=False)

### Load the second data & Preview

In [393]:
mobile_money

,countrynewwb,codewb,year,pop_adult,regionwb24_hi,incomegroupwb24,group,group2,account_t_d,fiaccount_t_d,mobileaccount_t_d,borrow_any_t_d
0,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.294254,0.294254,NaN,NaN
1,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.318453,0.318453,NaN,NaN
2,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.270883,0.270883,NaN,NaN
3,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.367447,0.367447,NaN,NaN
4,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.183889,0.183889,NaN,NaN
5,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.307487,0.307487,NaN,NaN
6,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.265399,0.265399,NaN,NaN
7,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.194271,0.194271,NaN,NaN
8,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.348870,0.348870,NaN,NaN
9,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.513962,0.513962,NaN,NaN
10,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.164517,0.164517,NaN,NaN
11,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.405058,0.346184,0.130066,0.366597
12,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.416712,0.352722,0.142127,0.379415
13,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.393773,0.339852,0.118387,0.354185
14,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.451520,0.389465,0.149733,0.389387
15,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.335196,0.281105,0.100493,0.332328
16,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.423422,0.383135,0.118232,0.413473
17,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.364242,0.264056,0.156366,0.262410
18,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.380945,0.305842,0.137954,0.278920
19,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.421371,0.373476,0.124729,0.425913
20,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.535526,0.470782,0.182589,0.380160
21,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.248726,0.196022,0.067259,0.352914
22,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.577175,0.422842,0.389478,0.402703
23,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.617917,0.462904,0.442139,0.430126
24,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.537234,0.383567,0.337851,0.375819
25,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.639443,0.482651,0.435465,0.412290
26,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.483441,0.332808,0.320251,0.388271
27,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.618940,0.481004,0.399768,0.414508
28,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.484648,0.293988,0.366680,0.376551
29,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.484686,0.323323,0.322881,0.290697
30,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.651237,0.502532,0.442806,0.492393
31,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.675496,0.512833,0.462085,0.410559
32,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.493871,0.341001,0.331718,0.395929
33,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.682304,0.391966,0.596879,0.522064
34,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.741800,0.472950,0.646229,0.567382
35,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.625809,0.315068,0.550019,0.479032
36,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.772025,0.487858,0.685273,0.522603
37,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.547195,0.247565,0.463769,0.521251
38,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.695161,0.437722,0.588757,0.533586
39,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.652243,0.284982,0.615871,0.495123
40,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.546809,0.212700,0.504557,0.441059
41,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.737102,0.464467,0.634217,0.554825
42,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.809737,0.508407,0.726296,0.539990
43,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.515909,0.238888,0.429253,0.502677
44,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.812430,0.387411,0.782814,0.742407
45,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.844194,0.466233,0.810432,0.767802
46,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.783104,0.314639,0.757316,0.718961
47,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.890316,0.494309,0.855772,0.714453
48,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.695783,0.227314,0.673546,0.784272
49,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.817894,0.458667,0.784935,0.767738
50,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.799672,0.221019,0.777861,0.683255
51,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,urbanicity,rural,0.764097,0.338227,0.739452,0.771736
52,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,urbanicity,urban,0.870073,0.446068,0.834527,0.707429
53,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.671876,0.123307,0.639921,0.639610
54,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.869898,0.495394,0.841238,0.784437
55,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.893603,0.485753,0.868977,0.750231
56,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.678810,0.225482,0.645921,0.732652

### Preview

In [394]:
mobile_money.head()

,countrynewwb,codewb,year,pop_adult,regionwb24_hi,incomegroupwb24,group,group2,account_t_d,fiaccount_t_d,mobileaccount_t_d,borrow_any_t_d
0,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.294254,0.294254,NaN,NaN
1,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.318453,0.318453,NaN,NaN
2,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.270883,0.270883,NaN,NaN
3,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.367447,0.367447,NaN,NaN
4,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.183889,0.183889,NaN,NaN

### Clean the columns

In [395]:
mobile_money.rename(columns={
    "countrynewwb":"Country",
    "codewb":"Code",
    "year":"Year",
    "pop_adult":"Population_Adult",
    "regionwb24_hi":"Region_Group",
    "incomegroupwb24":"Income_Group",
    "group":"Group_Type",
    "group2":"Demographic_Group",
    "account_t_d": "Account_Owner",
    "fiaccount_t_d": "Financial_Account",
    "mobileaccount_t_d": "Mobile_Account",
    "borrow_any_t_d":"Borrowed_Account"
}, inplace =True)

### Preview

In [396]:
mobile_money

,Country,Code,Year,Population_Adult,Region_Group,Income_Group,Group_Type,Demographic_Group,Account_Owner,Financial_Account,Mobile_Account,Borrowed_Account
0,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.294254,0.294254,NaN,NaN
1,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.318453,0.318453,NaN,NaN
2,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.270883,0.270883,NaN,NaN
3,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.367447,0.367447,NaN,NaN
4,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.183889,0.183889,NaN,NaN
5,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.307487,0.307487,NaN,NaN
6,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.265399,0.265399,NaN,NaN
7,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.194271,0.194271,NaN,NaN
8,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.348870,0.348870,NaN,NaN
9,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.513962,0.513962,NaN,NaN
10,Ghana,GHA,2011,15512209,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.164517,0.164517,NaN,NaN
11,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.405058,0.346184,0.130066,0.366597
12,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.416712,0.352722,0.142127,0.379415
13,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.393773,0.339852,0.118387,0.354185
14,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.451520,0.389465,0.149733,0.389387
15,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.335196,0.281105,0.100493,0.332328
16,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.423422,0.383135,0.118232,0.413473
17,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.364242,0.264056,0.156366,0.262410
18,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.380945,0.305842,0.137954,0.278920
19,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.421371,0.373476,0.124729,0.425913
20,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.535526,0.470782,0.182589,0.380160
21,Ghana,GHA,2014,16743744,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.248726,0.196022,0.067259,0.352914
22,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.577175,0.422842,0.389478,0.402703
23,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.617917,0.462904,0.442139,0.430126
24,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.537234,0.383567,0.337851,0.375819
25,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.639443,0.482651,0.435465,0.412290
26,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.483441,0.332808,0.320251,0.388271
27,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.618940,0.481004,0.399768,0.414508
28,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.484648,0.293988,0.366680,0.376551
29,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.484686,0.323323,0.322881,0.290697
30,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.651237,0.502532,0.442806,0.492393
31,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.675496,0.512833,0.462085,0.410559
32,Ghana,GHA,2017,18083712,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.493871,0.341001,0.331718,0.395929
33,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.682304,0.391966,0.596879,0.522064
34,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.741800,0.472950,0.646229,0.567382
35,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.625809,0.315068,0.550019,0.479032
36,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.772025,0.487858,0.685273,0.522603
37,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.547195,0.247565,0.463769,0.521251
38,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.695161,0.437722,0.588757,0.533586
39,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.652243,0.284982,0.615871,0.495123
40,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.546809,0.212700,0.504557,0.441059
41,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.737102,0.464467,0.634217,0.554825
42,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.809737,0.508407,0.726296,0.539990
43,Ghana,GHA,2021,20017745,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.515909,0.238888,0.429253,0.502677
44,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,all,all,0.812430,0.387411,0.782814,0.742407
45,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,gender,men,0.844194,0.466233,0.810432,0.767802
46,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,gender,women,0.783104,0.314639,0.757316,0.718961
47,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,income,richest 60%,0.890316,0.494309,0.855772,0.714453
48,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,income,poorest 40%,0.695783,0.227314,0.673546,0.784272
49,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,age 25+,0.817894,0.458667,0.784935,0.767738
50,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,age_cat,ages 15-24,0.799672,0.221019,0.777861,0.683255
51,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,urbanicity,rural,0.764097,0.338227,0.739452,0.771736
52,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,urbanicity,urban,0.870073,0.446068,0.834527,0.707429
53,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,out of laborforce,0.671876,0.123307,0.639921,0.639610
54,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,laborforce,in laborforce,0.869898,0.495394,0.841238,0.784437
55,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,education,secondary edu or more,0.893603,0.485753,0.868977,0.750231
56,Ghana,GHA,2024,21563813,Sub-Saharan Africa (excluding high income),Lower middle income,education,prim edu or less,0.678810,0.225482,0.645921,0.732652

### Drop unnecessary columns

In [397]:
mobile_money.drop(columns=["Code","Income_Group","Region_Group"], inplace= True)

In [398]:
mobile_money.head()

,Country,Year,Population_Adult,Group_Type,Demographic_Group,Account_Owner,Financial_Account,Mobile_Account,Borrowed_Account
0,Ghana,2011,15512209,all,all,0.294254,0.294254,NaN,NaN
1,Ghana,2011,15512209,gender,men,0.318453,0.318453,NaN,NaN
2,Ghana,2011,15512209,gender,women,0.270883,0.270883,NaN,NaN
3,Ghana,2011,15512209,income,richest 60%,0.367447,0.367447,NaN,NaN
4,Ghana,2011,15512209,income,poorest 40%,0.183889,0.183889,NaN,NaN

### Filter it to the  year range needed

In [399]:
mobile_money=mobile_money[mobile_money["Year"]>=2017].reset_index(drop=True)

In [400]:
mobile_money.head()

,Country,Year,Population_Adult,Group_Type,Demographic_Group,Account_Owner,Financial_Account,Mobile_Account,Borrowed_Account
0,Ghana,2017,18083712,all,all,0.577175,0.422842,0.389478,0.402703
1,Ghana,2017,18083712,gender,men,0.617917,0.462904,0.442139,0.430126
2,Ghana,2017,18083712,gender,women,0.537234,0.383567,0.337851,0.375819
3,Ghana,2017,18083712,income,richest 60%,0.639443,0.482651,0.435465,0.412290
4,Ghana,2017,18083712,income,poorest 40%,0.483441,0.332808,0.320251,0.388271

### Remove fully empty columns &  duplicates

In [401]:

mobile_money = mobile_money.dropna(axis=1, how='all')


mobile_money = mobile_money.drop_duplicates()

### Fix inconsistent text values

In [402]:
mobile_money[["Group_Type","Demographic_Group"]] = mobile_money[["Group_Type","Demographic_Group"]].replace({
    "all":"All",
    "income":"Income",
    "gender":"Gender",
    "men":"Men",
    "women":"Women",
    "richest 60%":"Richest 60%",
    "poorest 40%":"Poorest 40%",
    "age_cat":"Age_Category",
    "laborforce":"Labor Force",
    "in laborforce":"In Labor Force",
    "out of laborforce":"Out of Labor Force",
    "secondary edu or more":"Secondary  Education / Higher ",
    "prim edu or less":"Primary Education / Lower",
    "age 25+":"Adults (25+)",
    "ages 15-24":"Youth (15-24)",
    "urbanicity":"Urbanicity",
    "education":"Education",
    "urban":"Urban",
    "rural":"Rural"
},)

### Final preview

In [403]:
mobile_money

,Country,Year,Population_Adult,Group_Type,Demographic_Group,Account_Owner,Financial_Account,Mobile_Account,Borrowed_Account
0,Ghana,2017,18083712,All,All,0.577175,0.422842,0.389478,0.402703
1,Ghana,2017,18083712,Gender,Men,0.617917,0.462904,0.442139,0.430126
2,Ghana,2017,18083712,Gender,Women,0.537234,0.383567,0.337851,0.375819
3,Ghana,2017,18083712,Income,Richest 60%,0.639443,0.482651,0.435465,0.412290
4,Ghana,2017,18083712,Income,Poorest 40%,0.483441,0.332808,0.320251,0.388271
5,Ghana,2017,18083712,Age_Category,Adults (25+),0.618940,0.481004,0.399768,0.414508
6,Ghana,2017,18083712,Age_Category,Youth (15-24),0.484648,0.293988,0.366680,0.376551
7,Ghana,2017,18083712,Labor Force,Out of Labor Force,0.484686,0.323323,0.322881,0.290697
8,Ghana,2017,18083712,Labor Force,In Labor Force,0.651237,0.502532,0.442806,0.492393
9,Ghana,2017,18083712,Education,Secondary Education / Higher,0.675496,0.512833,0.462085,0.410559
10,Ghana,2017,18083712,Education,Primary Education / Lower,0.493871,0.341001,0.331718,0.395929
11,Ghana,2021,20017745,All,All,0.682304,0.391966,0.596879,0.522064
12,Ghana,2021,20017745,Gender,Men,0.741800,0.472950,0.646229,0.567382
13,Ghana,2021,20017745,Gender,Women,0.625809,0.315068,0.550019,0.479032
14,Ghana,2021,20017745,Income,Richest 60%,0.772025,0.487858,0.685273,0.522603
15,Ghana,2021,20017745,Income,Poorest 40%,0.547195,0.247565,0.463769,0.521251
16,Ghana,2021,20017745,Age_Category,Adults (25+),0.695161,0.437722,0.588757,0.533586
17,Ghana,2021,20017745,Age_Category,Youth (15-24),0.652243,0.284982,0.615871,0.495123
18,Ghana,2021,20017745,Labor Force,Out of Labor Force,0.546809,0.212700,0.504557,0.441059
19,Ghana,2021,20017745,Labor Force,In Labor Force,0.737102,0.464467,0.634217,0.554825
20,Ghana,2021,20017745,Education,Secondary Education / Higher,0.809737,0.508407,0.726296,0.539990
21,Ghana,2021,20017745,Education,Primary Education / Lower,0.515909,0.238888,0.429253,0.502677
22,Ghana,2024,21563813,All,All,0.812430,0.387411,0.782814,0.742407
23,Ghana,2024,21563813,Gender,Men,0.844194,0.466233,0.810432,0.767802
24,Ghana,2024,21563813,Gender,Women,0.783104,0.314639,0.757316,0.718961
25,Ghana,2024,21563813,Income,Richest 60%,0.890316,0.494309,0.855772,0.714453
26,Ghana,2024,21563813,Income,Poorest 40%,0.695783,0.227314,0.673546,0.784272
27,Ghana,2024,21563813,Age_Category,Adults (25+),0.817894,0.458667,0.784935,0.767738
28,Ghana,2024,21563813,Age_Category,Youth (15-24),0.799672,0.221019,0.777861,0.683255
29,Ghana,2024,21563813,Urbanicity,Rural,0.764097,0.338227,0.739452,0.771736
30,Ghana,2024,21563813,Urbanicity,Urban,0.870073,0.446068,0.834527,0.707429
31,Ghana,2024,21563813,Labor Force,Out of Labor Force,0.671876,0.123307,0.639921,0.639610
32,Ghana,2024,21563813,Labor Force,In Labor Force,0.869898,0.495394,0.841238,0.784437
33,Ghana,2024,21563813,Education,Secondary Education / Higher,0.893603,0.485753,0.868977,0.750231
34,Ghana,2024,21563813,Education,Primary Education / Lower,0.678810,0.225482,0.645921,0.732652

In [404]:
mobile_money.shape
mobile_money.isnull().sum()
mobile_money.duplicated().sum()

0

### Export cleaned data

In [405]:
mobile_money.to_excel(r"C:\Users\TOSHIBA\Desktop\py\Mobile Money.xlsx",index=False)

### Load the third dataset

In [406]:
interest_rate

,"Population (6 years and older) by Usedphone_financial, Education, Geographic_Area and Age",Unnamed: 1,Unnamed: 2,AGE RANGES,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,FINANCIAL TRANSACTIONS,EDUCATION,REGION,6-11,12-15,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85-89
1,Used mobile phone for financial transaction,Never attended,Western,301,229,2536,8937,13534,16570,17376,15200,13339,10249,7150,5477,3246,2337,1496,909,440
2,NaN,NaN,Central,252,213,2084,6952,11411,15495,19804,19863,19753,17082,13020,11445,7534,6100,4114,2832,1270
3,NaN,NaN,Greater Accra,445,364,4018,15255,25569,33860,36352,32620,28046,21661,14926,12322,7520,5673,3563,2193,1087
4,NaN,NaN,Volta,141,95,959,3489,5607,8171,9604,9610,9850,9324,7316,6519,4366,3731,2864,2481,1392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,NaN,NaN,Northern,0,0,0,7,18,9,11,3,15,4,1,2,4,2,3,0,0
1277,NaN,NaN,Savannah,0,0,0,3,2,2,2,3,1,0,4,0,0,0,0,0,0
1278,NaN,NaN,North East,0,0,0,6,3,0,3,1,0,2,3,0,0,0,1,0,0
1279,NaN,NaN,Upper East,0,0,0,4,5,8,8,7,7,8,3,0,1,0,0,0,0
1280,NaN,NaN,Upper West,0,0,0,3,2,5,7,1,1,4,4,2,1,3,1,2,1

### Fix multi-row header issue

In [407]:
interest_rate.columns=interest_rate.iloc[0].astype(str)+ " "+interest_rate.columns.astype(str)

In [408]:
interest_rate

,"FINANCIAL TRANSACTIONS Population (6 years and older) by Usedphone_financial, Education, Geographic_Area and Age",EDUCATION Unnamed: 1,REGION Unnamed: 2,6-11 AGE RANGES,12-15 Unnamed: 4,15-19 Unnamed: 5,20-24 Unnamed: 6,25-29 Unnamed: 7,30-34 Unnamed: 8,35-39 Unnamed: 9,40-44 Unnamed: 10,45-49 Unnamed: 11,50-54 Unnamed: 12,55-59 Unnamed: 13,60-64 Unnamed: 14,65-69 Unnamed: 15,70-74 Unnamed: 16,75-79 Unnamed: 17,80-84 Unnamed: 18,85-89 Unnamed: 19
0,FINANCIAL TRANSACTIONS,EDUCATION,REGION,6-11,12-15,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85-89
1,Used mobile phone for financial transaction,Never attended,Western,301,229,2536,8937,13534,16570,17376,15200,13339,10249,7150,5477,3246,2337,1496,909,440
2,NaN,NaN,Central,252,213,2084,6952,11411,15495,19804,19863,19753,17082,13020,11445,7534,6100,4114,2832,1270
3,NaN,NaN,Greater Accra,445,364,4018,15255,25569,33860,36352,32620,28046,21661,14926,12322,7520,5673,3563,2193,1087
4,NaN,NaN,Volta,141,95,959,3489,5607,8171,9604,9610,9850,9324,7316,6519,4366,3731,2864,2481,1392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,NaN,NaN,Northern,0,0,0,7,18,9,11,3,15,4,1,2,4,2,3,0,0
1277,NaN,NaN,Savannah,0,0,0,3,2,2,2,3,1,0,4,0,0,0,0,0,0
1278,NaN,NaN,North East,0,0,0,6,3,0,3,1,0,2,3,0,0,0,1,0,0
1279,NaN,NaN,Upper East,0,0,0,4,5,8,8,7,7,8,3,0,1,0,0,0,0
1280,NaN,NaN,Upper West,0,0,0,3,2,5,7,1,1,4,4,2,1,3,1,2,1

### remove the first row

In [409]:
interest_rate =interest_rate.drop(index=0).reset_index(drop=True)

In [410]:
interest_rate

,"FINANCIAL TRANSACTIONS Population (6 years and older) by Usedphone_financial, Education, Geographic_Area and Age",EDUCATION Unnamed: 1,REGION Unnamed: 2,6-11 AGE RANGES,12-15 Unnamed: 4,15-19 Unnamed: 5,20-24 Unnamed: 6,25-29 Unnamed: 7,30-34 Unnamed: 8,35-39 Unnamed: 9,40-44 Unnamed: 10,45-49 Unnamed: 11,50-54 Unnamed: 12,55-59 Unnamed: 13,60-64 Unnamed: 14,65-69 Unnamed: 15,70-74 Unnamed: 16,75-79 Unnamed: 17,80-84 Unnamed: 18,85-89 Unnamed: 19
0,Used mobile phone for financial transaction,Never attended,Western,301,229,2536,8937,13534,16570,17376,15200,13339,10249,7150,5477,3246,2337,1496,909,440
1,NaN,NaN,Central,252,213,2084,6952,11411,15495,19804,19863,19753,17082,13020,11445,7534,6100,4114,2832,1270
2,NaN,NaN,Greater Accra,445,364,4018,15255,25569,33860,36352,32620,28046,21661,14926,12322,7520,5673,3563,2193,1087
3,NaN,NaN,Volta,141,95,959,3489,5607,8171,9604,9610,9850,9324,7316,6519,4366,3731,2864,2481,1392
4,NaN,NaN,Eastern,281,185,1936,6001,9783,13676,16946,16817,16153,14330,11064,9525,6453,5611,3724,2982,1760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,NaN,NaN,Northern,0,0,0,7,18,9,11,3,15,4,1,2,4,2,3,0,0
1276,NaN,NaN,Savannah,0,0,0,3,2,2,2,3,1,0,4,0,0,0,0,0,0
1277,NaN,NaN,North East,0,0,0,6,3,0,3,1,0,2,3,0,0,0,1,0,0
1278,NaN,NaN,Upper East,0,0,0,4,5,8,8,7,7,8,3,0,1,0,0,0,0
1279,NaN,NaN,Upper West,0,0,0,3,2,5,7,1,1,4,4,2,1,3,1,2,1

### Reclean the columns

In [411]:
interest_rate.rename(columns={
"FINANCIAL TRANSACTIONS Population (6 years and older) by Usedphone_financial, Education, Geographic_Area and Age":"Transactional_Type",
"EDUCATION Unnamed: 1":"Education_Level",
"REGION Unnamed: 2":"Region",
"6-11 AGE RANGES":"Age(6-11)",
"12-15 Unnamed: 4":"Age(12-15)",
"15-19 Unnamed: 5":"Age(15-19)",
"20-24 Unnamed: 6":"Age(20-24)",
"25-29 Unnamed: 7":"Age(25-29)",
"30-34 Unnamed: 8":"Age(30-34)",
"35-39 Unnamed: 9":"Age(35-39)",
"40-44 Unnamed: 10":"Age(40-44)",
"45-49 Unnamed: 11":"Age(45-49)",
"50-54 Unnamed: 12":"Age(50-54)",
"55-59 Unnamed: 13":"Age(55-59)",
"60-64 Unnamed: 14":"Age(60-64)",
"65-69 Unnamed: 15":"Age(65-69)",
"70-74 Unnamed: 16":"Age(70-74)",
"75-79 Unnamed: 17":"Age(75-79)",
"80-84 Unnamed: 18":"Age(80-84)",
"85-89 Unnamed: 19":"Age(85-89)"
},inplace=True)

### Handle missing values
### Replace empty strings with NaN
### Forward fill only when it makes sense

In [412]:
interest_rate["Education_Level"]=interest_rate["Education_Level"].replace("",pd.NA)

In [413]:
interest_rate["Education_Level"]=interest_rate["Education_Level"].ffill()

In [414]:
interest_rate

,Transactional_Type,Education_Level,Region,Age(6-11),Age(12-15),Age(15-19),Age(20-24),Age(25-29),Age(30-34),Age(35-39),Age(40-44),Age(45-49),Age(50-54),Age(55-59),Age(60-64),Age(65-69),Age(70-74),Age(75-79),Age(80-84),Age(85-89)
0,Used mobile phone for financial transaction,Never attended,Western,301,229,2536,8937,13534,16570,17376,15200,13339,10249,7150,5477,3246,2337,1496,909,440
1,NaN,Never attended,Central,252,213,2084,6952,11411,15495,19804,19863,19753,17082,13020,11445,7534,6100,4114,2832,1270
2,NaN,Never attended,Greater Accra,445,364,4018,15255,25569,33860,36352,32620,28046,21661,14926,12322,7520,5673,3563,2193,1087
3,NaN,Never attended,Volta,141,95,959,3489,5607,8171,9604,9610,9850,9324,7316,6519,4366,3731,2864,2481,1392
4,NaN,Never attended,Eastern,281,185,1936,6001,9783,13676,16946,16817,16153,14330,11064,9525,6453,5611,3724,2982,1760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,NaN,Tertiary - PhD,Northern,0,0,0,7,18,9,11,3,15,4,1,2,4,2,3,0,0
1276,NaN,Tertiary - PhD,Savannah,0,0,0,3,2,2,2,3,1,0,4,0,0,0,0,0,0
1277,NaN,Tertiary - PhD,North East,0,0,0,6,3,0,3,1,0,2,3,0,0,0,1,0,0
1278,NaN,Tertiary - PhD,Upper East,0,0,0,4,5,8,8,7,7,8,3,0,1,0,0,0,0
1279,NaN,Tertiary - PhD,Upper West,0,0,0,3,2,5,7,1,1,4,4,2,1,3,1,2,1

In [415]:
interest_rate["Transactional_Type"] = interest_rate["Transactional_Type"].replace("",pd.NA)

In [416]:
interest_rate["Transactional_Type"] = interest_rate["Transactional_Type"].ffill()

In [417]:
interest_rate

,Transactional_Type,Education_Level,Region,Age(6-11),Age(12-15),Age(15-19),Age(20-24),Age(25-29),Age(30-34),Age(35-39),Age(40-44),Age(45-49),Age(50-54),Age(55-59),Age(60-64),Age(65-69),Age(70-74),Age(75-79),Age(80-84),Age(85-89)
0,Used mobile phone for financial transaction,Never attended,Western,301,229,2536,8937,13534,16570,17376,15200,13339,10249,7150,5477,3246,2337,1496,909,440
1,Used mobile phone for financial transaction,Never attended,Central,252,213,2084,6952,11411,15495,19804,19863,19753,17082,13020,11445,7534,6100,4114,2832,1270
2,Used mobile phone for financial transaction,Never attended,Greater Accra,445,364,4018,15255,25569,33860,36352,32620,28046,21661,14926,12322,7520,5673,3563,2193,1087
3,Used mobile phone for financial transaction,Never attended,Volta,141,95,959,3489,5607,8171,9604,9610,9850,9324,7316,6519,4366,3731,2864,2481,1392
4,Used mobile phone for financial transaction,Never attended,Eastern,281,185,1936,6001,9783,13676,16946,16817,16153,14330,11064,9525,6453,5611,3724,2982,1760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,Did not use mobile phone for financial transac...,Tertiary - PhD,Northern,0,0,0,7,18,9,11,3,15,4,1,2,4,2,3,0,0
1276,Did not use mobile phone for financial transac...,Tertiary - PhD,Savannah,0,0,0,3,2,2,2,3,1,0,4,0,0,0,0,0,0
1277,Did not use mobile phone for financial transac...,Tertiary - PhD,North East,0,0,0,6,3,0,3,1,0,2,3,0,0,0,1,0,0
1278,Did not use mobile phone for financial transac...,Tertiary - PhD,Upper East,0,0,0,4,5,8,8,7,7,8,3,0,1,0,0,0,0
1279,Did not use mobile phone for financial transac...,Tertiary - PhD,Upper West,0,0,0,3,2,5,7,1,1,4,4,2,1,3,1,2,1

### Remove fully empty columns & duplicates

In [418]:
interest_rate= interest_rate.dropna(axis=1, how='all')
interest_rate = interest_rate.drop_duplicates()

In [419]:
interest_rate.shape
interest_rate.isnull().sum()
interest_rate.duplicated().sum()

0

### Export clean dataset

In [420]:
interest_rate.to_excel(r"C:\Users\TOSHIBA\Desktop\py\Interest Rate.xlsx",index=False)